FROM python:3.11-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY orchestrator/ /app/orchestrator/
COPY workers/ /app/workers/
RUN mkdir -p /app/logs
COPY . /app

ENV PYTHONPATH=/app
CMD ["sh", "-c", "python workers/${WORKER_TYPE}/worker.py"]
